const LABELS: Record<string, string> = {
  fact: 'Факты',
  derived: 'Вычисленные показатели',
  hints: 'Подсказки и ограничения',
  operator: 'Оператор',
  schedule: 'Расписание',
  today: 'Сегодня',
  recent: 'Недавнее',
  yesterdayPendingMissions: 'Вчерашние незакрытые миссии',
  foundation: 'Фундамент',
  regulation: 'Регуляция',
  mind: 'Разум',
  influence: 'Влияние',
  operations: 'Операции',
  doctrine: 'Доктрина',
  readingProgress: 'Чтение',
  readiness: 'Готовность',
  moduleStatuses: 'Статусы модулей',
  operatorMode: 'Режим оператора',
  stageProgress: 'Прогресс стадий',
  compliance: 'Соблюдение протокола',
  integration: 'Интеграция',
  constraints: 'Ограничения',
  aiMode: 'Режим ИИ',
  ruleHints: 'Правила-подсказки',
  date: 'Дата',
  contextLookbackDays: 'Период анализа (дней)',
  contextSinceDate: 'Данные с даты',
  scope: 'Область',
  codename: 'Позывной',
  goals: 'Цели',
  currentStage: 'Текущая стадия',
  unlockedStages: 'Открытые стадии',
  startDate: 'Дата старта',
  todayQueue: 'Очередь на сегодня',
  weekTemplateDays: 'Дней в шаблоне недели',
  pendingSlots: 'Ожидающих слотов',
  missions: 'Миссии',
  protocol: 'Протокол',
  dailyLog: 'Дневной лог',
  briefingDone: 'Briefing выполнен',
  debriefDone: 'Debrief выполнен',
  title: 'Название',
  priority: 'Приоритет',
  status: 'Статус',
  stage: 'Стадия',
  taskKey: 'Ключ задачи',
  label: 'Метка',
  done: 'Выполнено',
  rank: 'Ранг',
  type: 'Тип',
  global: 'Общая',
  foundation_score: 'Фундамент',
  regulation_score: 'Регуляция',
  mind_score: 'Разум',
  influence_score: 'Влияние',
  hrvRecent: 'HRV (недавние)',
  breathing7d: 'Дыхание за 7 дней',
  hrvTrendInWindow: 'Тренд HRV',
  hrvBaseline14d: 'Базовый HRV (14 дн.)',
  readinessRegulation: 'Готовность: регуляция',
  readinessFoundation: 'Готовность: фундамент',
  cognitiveThrottle: 'Ограничение когнитивной нагрузки',
  throttle: 'Ограничение коммуникации',
  ops7d: 'Операции за 7 дней',
  recentScenarios: 'Недавние сценарии',
  recentDecisions: 'Недавние решения',
  studySessionsInWindow: 'Сессии обучения',
  pendingDecisionFollowUps: 'Отложенные решения',
  recentEntries: 'Недавние записи',
  contacts: 'Контакты',
  contactsSummary: 'Сводка контактов',
  active: 'Активные',
  overdue: 'Просроченные',
  rules: 'Правила',
  mode: 'Режим',
  stages: 'Стадии пирамиды',
  synergy: 'Синергия',
  pdp: 'План развития (PDP)',
  lastWeeklyAudit: 'Последний недельный аудит',
  fitnessLevels: 'Уровни фитнеса',
  workoutPlanToday: 'План тренировки сегодня',
  setLogsSummary: 'Сводка подходов',
  bftHistory: 'История BFT',
  acftHistory: 'История ACFT',
  equipmentConstraints: 'Ограничения по оборудованию',
  allowed: 'Разрешено',
  forbidden: 'Запрещено',
  activeWorkoutRequest: 'Запрос тренировки',
  gppRotationNext: 'Следующий GPP в ротации',
  exerciseCatalog: 'Каталог упражнений',
  allowedExerciseIds: 'Разрешённые упражнения',
  trendInWindow: 'Тренд за период',
  yesterday: 'Вчера',
  stageStreaks: 'Серии по стадиям',
  globalStreak: 'Общая серия',
  pendingAdvance: 'Ожидает повышения',
  pendingDemotion: 'Ожидает понижения',
  qualifyingDays: 'Квалифицирующие дни',
  failedBlockers: 'Блокеры',
  createdAt: 'Создано',
  preview: 'Превью',
  deadline: 'Дедлайн',
  phase: 'Фаза',
  followUpDueDate: 'Срок follow-up',
  expectedOutcome: 'Ожидаемый результат',
  role: 'Роль',
  motives: 'Мотивы',
  disclosureNotes: 'Заметки раскрытия',
};

export function labelForKey(key: string): string {
  if (LABELS[key]) return LABELS[key];
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .trim()
    .replace(/^\w/, (c) => c.toUpperCase());
}
