import type { CatalogExercise } from '@/core/domain/types';
import { allTiers, defineExercise, tiersFromMin } from './catalog-utils';

const K: CatalogExercise['workoutKinds'] = ['warmup'];

export const WARMUP_EXERCISES: CatalogExercise[] = [
  defineExercise({ id: 'warm_jog', name: 'Лёгкий бег на месте', pattern: 'legs', equipment: 'none', muscles: ['cardio'], difficulty: 1, defaultRestSec: 15, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 60 }),
  defineExercise({ id: 'warm_march', name: 'Марш на месте', pattern: 'legs', equipment: 'none', muscles: ['cardio'], difficulty: 1, defaultRestSec: 15, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 45 }),
  defineExercise({ id: 'warm_arm_circles', name: 'Круги руками', pattern: 'push', equipment: 'none', muscles: ['shoulders'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 20 }),
  defineExercise({ id: 'warm_leg_swings', name: 'Махи ногами', pattern: 'legs', equipment: 'none', muscles: ['hips'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 16 }),
  defineExercise({ id: 'warm_hip_circles', name: 'Круги бёдрами', pattern: 'legs', equipment: 'none', muscles: ['hips'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'warm_cat_cow', name: 'Кошка-корова', pattern: 'core', equipment: 'none', muscles: ['spine'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'warm_inchworm', name: 'Гусеница', pattern: 'core', equipment: 'none', muscles: ['full'], difficulty: 2, defaultRestSec: 20, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 6 }),
  defineExercise({ id: 'warm_world_greatest', name: 'Величайший растяж', pattern: 'legs', equipment: 'none', muscles: ['hips'], difficulty: 2, defaultRestSec: 20, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 6 }),
  defineExercise({ id: 'warm_jump_jack', name: 'Прыжки джампинг', pattern: 'legs', equipment: 'none', muscles: ['cardio'], difficulty: 2, defaultRestSec: 20, progressionRule: 'reps+2', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'reps', defaultTargetReps: 20 }),
  defineExercise({ id: 'warm_high_knee', name: 'Высокие колени', pattern: 'legs', equipment: 'none', muscles: ['cardio'], difficulty: 2, defaultRestSec: 20, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30 }),
  defineExercise({ id: 'warm_butt_kick', name: 'Пятки к ягодицам', pattern: 'legs', equipment: 'none', muscles: ['cardio'], difficulty: 1, defaultRestSec: 15, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30 }),
  defineExercise({ id: 'warm_squat', name: 'Приседания лёгкие', pattern: 'legs', equipment: 'none', muscles: ['quads'], difficulty: 1, defaultRestSec: 20, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 15 }),
  defineExercise({ id: 'warm_lunge_walk', name: 'Выпады на месте', pattern: 'legs', equipment: 'none', muscles: ['quads'], difficulty: 1, defaultRestSec: 20, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'warm_pushup_incline', name: 'Отжимания лёгкие', pattern: 'push', equipment: 'bar', muscles: ['chest'], difficulty: 1, defaultRestSec: 20, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'warm_scap', name: 'Скапулярные', pattern: 'pull', equipment: 'bar', muscles: ['back'], difficulty: 1, defaultRestSec: 20, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'warm_hang_short', name: 'Короткий вис', pattern: 'pull', equipment: 'bar', muscles: ['grip'], difficulty: 1, defaultRestSec: 20, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 15 }),
  defineExercise({ id: 'warm_australian_light', name: 'Австралийские лёгкие', pattern: 'pull', equipment: 'bar', muscles: ['back'], difficulty: 1, defaultRestSec: 25, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'warm_dip_assist', name: 'Брусья лёгкие', pattern: 'push', equipment: 'dip', muscles: ['chest'], difficulty: 1, defaultRestSec: 25, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'warm_plank_short', name: 'Планка короткая', pattern: 'core', equipment: 'none', muscles: ['core'], difficulty: 1, defaultRestSec: 15, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 20, isStatic: true }),
  defineExercise({ id: 'warm_torso_twist', name: 'Повороты корпуса', pattern: 'core', equipment: 'none', muscles: ['obliques'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 16 }),
  defineExercise({ id: 'warm_neck', name: 'Шея (медленно)', pattern: 'core', equipment: 'none', muscles: ['neck'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'warm_wrist', name: 'Запястья', pattern: 'push', equipment: 'none', muscles: ['forearms'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'warm_ankle', name: 'Голеностоп', pattern: 'legs', equipment: 'none', muscles: ['ankles'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'warm_shoulder_disloc', name: 'Разгибание плеч (палка/полотенце)', pattern: 'push', equipment: 'none', muscles: ['shoulders'], difficulty: 2, defaultRestSec: 20, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'warm_bear_crawl', name: 'Медведь (коротко)', pattern: 'core', equipment: 'none', muscles: ['full'], difficulty: 2, defaultRestSec: 25, progressionRule: 'time+5s', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'seconds', defaultTargetSec: 20 }),
  defineExercise({ id: 'warm_skip', name: 'Скакалка без верёвки', pattern: 'legs', equipment: 'none', muscles: ['cardio'], difficulty: 2, defaultRestSec: 20, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 45 }),
  defineExercise({ id: 'warm_side_lunge', name: 'Боковые выпады', pattern: 'legs', equipment: 'none', muscles: ['hips'], difficulty: 1, defaultRestSec: 20, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'warm_calf', name: 'Икры', pattern: 'legs', equipment: 'none', muscles: ['calves'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 15 }),
  defineExercise({ id: 'warm_glute_bridge', name: 'Мост', pattern: 'legs', equipment: 'none', muscles: ['glutes'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'warm_dead_bug', name: 'Dead bug', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 1, defaultRestSec: 15, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'warm_breath', name: 'Дыхание 4-4-4', pattern: 'core', equipment: 'none', muscles: ['recovery'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 60, isStatic: true }),
];
