import type { CatalogExercise } from '@/core/domain/types';
import { allTiers, defineExercise, tiersFromMin } from './catalog-utils';

const K: CatalogExercise['workoutKinds'] = ['stretch'];

export const STRETCH_EXERCISES: CatalogExercise[] = [
  defineExercise({ id: 'str_hamstring', name: 'Задняя поверхность бедра', pattern: 'legs', equipment: 'none', muscles: ['hamstrings'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 45, isStatic: true }),
  defineExercise({ id: 'str_quad', name: 'Квадрицепс стоя', pattern: 'legs', equipment: 'none', muscles: ['quads'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 40, isStatic: true }),
  defineExercise({ id: 'str_hip_flexor', name: 'Сгибатели бедра', pattern: 'legs', equipment: 'none', muscles: ['hip_flexors'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 40, isStatic: true }),
  defineExercise({ id: 'str_pigeon', name: 'Голубь', pattern: 'legs', equipment: 'none', muscles: ['glutes'], difficulty: 2, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 45, isStatic: true }),
  defineExercise({ id: 'str_figure4', name: 'Четвёрка', pattern: 'legs', equipment: 'none', muscles: ['glutes'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 40, isStatic: true }),
  defineExercise({ id: 'str_calf_wall', name: 'Икры у стены', pattern: 'legs', equipment: 'none', muscles: ['calves'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 40, isStatic: true }),
  defineExercise({ id: 'str_lat_door', name: 'Широчайшие (дверной косяк)', pattern: 'pull', equipment: 'none', muscles: ['lat'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 35, isStatic: true }),
  defineExercise({ id: 'str_chest_door', name: 'Грудные у стены', pattern: 'push', equipment: 'none', muscles: ['chest'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 35, isStatic: true }),
  defineExercise({ id: 'str_triceps', name: 'Трицепс', pattern: 'push', equipment: 'none', muscles: ['triceps'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'str_shoulder_cross', name: 'Плечо поперёк', pattern: 'push', equipment: 'none', muscles: ['shoulders'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'str_neck_side', name: 'Шея бок', pattern: 'core', equipment: 'none', muscles: ['neck'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 25, isStatic: true }),
  defineExercise({ id: 'str_cat_cow_slow', name: 'Кошка-корова медленно', pattern: 'core', equipment: 'none', muscles: ['spine'], difficulty: 1, defaultRestSec: 10, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'str_child_pose', name: 'Поза ребёнка', pattern: 'core', equipment: 'none', muscles: ['back'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 50, isStatic: true }),
  defineExercise({ id: 'str_down_dog', name: 'Собака мордой вниз', pattern: 'push', equipment: 'none', muscles: ['full'], difficulty: 2, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 40, isStatic: true }),
  defineExercise({ id: 'str_up_dog', name: 'Собака вверх', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 2, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'str_spinal_twist', name: 'Скручивание лёжа', pattern: 'core', equipment: 'none', muscles: ['spine'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 40, isStatic: true }),
  defineExercise({ id: 'str_butterfly', name: 'Бабочка', pattern: 'legs', equipment: 'none', muscles: ['adductors'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 45, isStatic: true }),
  defineExercise({ id: 'str_straddle', name: 'Поперечный шпагат (подготовка)', pattern: 'legs', equipment: 'none', muscles: ['adductors'], difficulty: 3, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'seconds', defaultTargetSec: 40, isStatic: true }),
  defineExercise({ id: 'str_hang_relax', name: 'Расслабленный вис', pattern: 'pull', equipment: 'bar', muscles: ['spine'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'str_bar_shoulder', name: 'Плечи на турнике', pattern: 'pull', equipment: 'bar', muscles: ['shoulders'], difficulty: 2, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'str_forearm', name: 'Предплечья', pattern: 'pull', equipment: 'none', muscles: ['forearms'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'str_wrist', name: 'Запястья', pattern: 'push', equipment: 'none', muscles: ['wrists'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 25, isStatic: true }),
  defineExercise({ id: 'str_hip_90', name: '90/90 бёдра', pattern: 'legs', equipment: 'none', muscles: ['hips'], difficulty: 2, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 40, isStatic: true }),
  defineExercise({ id: 'str_thoracic', name: 'Грудной отдел (ролл)', pattern: 'core', equipment: 'none', muscles: ['t_spine'], difficulty: 2, defaultRestSec: 10, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'str_scorpion', name: 'Скорпион (лёжа)', pattern: 'core', equipment: 'none', muscles: ['hips'], difficulty: 3, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'seconds', defaultTargetSec: 35, isStatic: true }),
  defineExercise({ id: 'str_lizard', name: 'Ящерица', pattern: 'legs', equipment: 'none', muscles: ['hip_flexors'], difficulty: 2, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 40, isStatic: true }),
  defineExercise({ id: 'str_samson', name: 'Самсон', pattern: 'legs', equipment: 'none', muscles: ['hip_flexors'], difficulty: 2, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 35, isStatic: true }),
  defineExercise({ id: 'str_supine_twist', name: 'Скручивание сидя', pattern: 'core', equipment: 'none', muscles: ['obliques'], difficulty: 1, defaultRestSec: 10, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 35, isStatic: true }),
  defineExercise({ id: 'str_box_breath', name: 'Дыхание box 4-4-4-4', pattern: 'core', equipment: 'none', muscles: ['recovery'], difficulty: 1, defaultRestSec: 5, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 60, isStatic: true }),
  defineExercise({ id: 'str_legs_up', name: 'Ноги на стену', pattern: 'legs', equipment: 'none', muscles: ['recovery'], difficulty: 1, defaultRestSec: 5, progressionRule: 'time+15s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 90, isStatic: true }),
  defineExercise({ id: 'str_full_body', name: 'Полное расслабление', pattern: 'core', equipment: 'none', muscles: ['full'], difficulty: 1, defaultRestSec: 5, progressionRule: 'time+15s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 120, isStatic: true }),
];
