import type { CatalogExercise } from '@/core/domain/types';
import { allTiers, defineExercise, tiersFromMin } from './catalog-utils';

const K: CatalogExercise['workoutKinds'] = ['gpp_push'];

export const GPP_PUSH_EXERCISES: CatalogExercise[] = [
  defineExercise({ id: 'gpp_push_dip', name: 'Отжимания на брусьях', pattern: 'push', equipment: 'dip', muscles: ['chest'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_push_dip_assist', name: 'Брусья с ногами', pattern: 'push', equipment: 'dip', muscles: ['chest'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('beginner'), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_push_dip_neg', name: 'Негативы брусья', pattern: 'push', equipment: 'dip', muscles: ['chest'], difficulty: 2, defaultRestSec: 90, progressionRule: 'slow', workoutKinds: K, tiers: tiersFromMin('beginner'), measure: 'reps', defaultTargetReps: 4 }),
  defineExercise({ id: 'gpp_push_bar', name: 'Отжимания от турника', pattern: 'push', equipment: 'bar', muscles: ['chest'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_push_pike', name: 'Пике-отжимания', pattern: 'push', equipment: 'none', muscles: ['shoulders'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_push_decline', name: 'Отжимания ноги выше', pattern: 'push', equipment: 'none', muscles: ['chest'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_push_diamond', name: 'Алмазные', pattern: 'push', equipment: 'none', muscles: ['triceps'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_push_wide', name: 'Широкие отжимания', pattern: 'push', equipment: 'none', muscles: ['chest'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_push_close', name: 'Узкие отжимания', pattern: 'push', equipment: 'none', muscles: ['triceps'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_push_tempo', name: 'Темповые отжимания (3-1-3)', pattern: 'push', equipment: 'none', muscles: ['chest'], difficulty: 3, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_push_archer', name: 'Арчер отжимания', pattern: 'push', equipment: 'none', muscles: ['chest'], difficulty: 5, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 4 }),
  defineExercise({ id: 'gpp_push_hspu_wall', name: 'Стеновые HSPU (подготовка)', pattern: 'push', equipment: 'none', muscles: ['shoulders'], difficulty: 4, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 5 }),
  defineExercise({ id: 'gpp_push_dip_pause', name: 'Брусья с паузой внизу', pattern: 'push', equipment: 'dip', muscles: ['chest'], difficulty: 4, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 6 }),
  defineExercise({ id: 'gpp_push_ring_support', name: 'Удержание на брусьях', pattern: 'push', equipment: 'dip', muscles: ['shoulders'], difficulty: 2, defaultRestSec: 60, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 20, isStatic: true }),
  defineExercise({ id: 'gpp_push_planche_lean', name: 'Наклон в планш (подготовка)', pattern: 'push', equipment: 'none', muscles: ['shoulders'], difficulty: 4, defaultRestSec: 75, progressionRule: 'time+3s', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'seconds', defaultTargetSec: 15, isStatic: true }),
  defineExercise({ id: 'gpp_push_incline', name: 'Отжимания ноги на турнике', pattern: 'push', equipment: 'bar', muscles: ['chest'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_push_clap', name: 'Взрывные отжимания', pattern: 'push', equipment: 'none', muscles: ['chest'], difficulty: 4, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 6 }),
  defineExercise({ id: 'gpp_push_knee', name: 'Отжимания с колен', pattern: 'push', equipment: 'none', muscles: ['chest'], difficulty: 1, defaultRestSec: 45, progressionRule: 'reps+2', workoutKinds: K, tiers: tiersFromMin('beginner'), measure: 'reps', defaultTargetReps: 15 }),
  defineExercise({ id: 'gpp_push_elevated', name: 'Отжимания руки на брусьях', pattern: 'push', equipment: 'dip', muscles: ['chest'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_push_serratus', name: 'Проскальзывание лопаток', pattern: 'push', equipment: 'bar', muscles: ['serratus'], difficulty: 1, defaultRestSec: 45, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 15 }),
  defineExercise({ id: 'gpp_push_ytw', name: 'Y-T-W на земле', pattern: 'push', equipment: 'none', muscles: ['rear_delt'], difficulty: 1, defaultRestSec: 45, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_push_shoulder_tap', name: 'Отжимания касание плеча', pattern: 'push', equipment: 'none', muscles: ['core', 'chest'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_push_spiderman', name: 'Спайдермен отжимания', pattern: 'push', equipment: 'none', muscles: ['chest'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_push_hindu', name: 'Индийские отжимания', pattern: 'push', equipment: 'none', muscles: ['shoulders'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_push_dip_bw', name: 'Отжимания между брусьями (низ)', pattern: 'push', equipment: 'dip', muscles: ['chest'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_push_plank_shoulder', name: 'Планка → отжимание', pattern: 'push', equipment: 'none', muscles: ['core'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_push_wall_handstand', name: 'Стойка у стены (удержание)', pattern: 'push', equipment: 'none', muscles: ['shoulders'], difficulty: 4, defaultRestSec: 90, progressionRule: 'time+5s', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'seconds', defaultTargetSec: 25, isStatic: true }),
  defineExercise({ id: 'gpp_push_plank_hold', name: 'Планка (статика)', pattern: 'core', equipment: 'none', muscles: ['core'], difficulty: 1, defaultRestSec: 45, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 45, isStatic: true }),
  defineExercise({ id: 'gpp_push_side_plank', name: 'Боковая планка', pattern: 'core', equipment: 'none', muscles: ['obliques'], difficulty: 2, defaultRestSec: 45, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'gpp_push_hollow', name: 'Hollow hold', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 2, defaultRestSec: 45, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 35, isStatic: true }),
  defineExercise({ id: 'gpp_push_mu_neg', name: 'Негатив выхода (push finisher)', pattern: 'push', equipment: 'bar', muscles: ['full'], difficulty: 5, defaultRestSec: 120, progressionRule: 'quality', workoutKinds: K, tiers: tiersFromMin('ayanakoji'), measure: 'reps', defaultTargetReps: 3 }),
];
