import type { CatalogExercise } from '@/core/domain/types';
import { allTiers, defineExercise, tiersFromMin } from './catalog-utils';

const K: CatalogExercise['workoutKinds'] = ['gpp_core'];

export const GPP_CORE_EXERCISES: CatalogExercise[] = [
  defineExercise({ id: 'gpp_core_plank', name: 'Планка', pattern: 'core', equipment: 'none', muscles: ['core'], difficulty: 1, defaultRestSec: 45, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 45, isStatic: true }),
  defineExercise({ id: 'gpp_core_side_plank', name: 'Боковая планка', pattern: 'core', equipment: 'none', muscles: ['obliques'], difficulty: 2, defaultRestSec: 45, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 35, isStatic: true }),
  defineExercise({ id: 'gpp_core_hollow', name: 'Hollow hold', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 2, defaultRestSec: 45, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 35, isStatic: true }),
  defineExercise({ id: 'gpp_core_arch', name: 'Superman hold', pattern: 'core', equipment: 'none', muscles: ['back'], difficulty: 1, defaultRestSec: 45, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'gpp_core_knee_raise', name: 'Подъём коленей', pattern: 'core', equipment: 'bar', muscles: ['abs'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_core_leg_raise', name: 'Подъём ног в висе на турнике', pattern: 'core', equipment: 'bar', muscles: ['abs'], difficulty: 4, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 11 }),
  defineExercise({ id: 'gpp_core_lsit_tuck', name: 'Уголок на брусьях (L-sit hold)', pattern: 'core', equipment: 'bar', muscles: ['abs'], difficulty: 3, defaultRestSec: 60, progressionRule: 'time+3s', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'seconds', defaultTargetSec: 20, isStatic: true }),
  defineExercise({ id: 'gpp_core_lsit', name: 'L-sit прямые', pattern: 'core', equipment: 'bar', muscles: ['abs'], difficulty: 5, defaultRestSec: 75, progressionRule: 'time+2s', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'seconds', defaultTargetSec: 12, isStatic: true }),
  defineExercise({ id: 'gpp_core_crunch', name: 'Скручивания', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 1, defaultRestSec: 45, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 20 }),
  defineExercise({ id: 'gpp_core_bicycle', name: 'Велосипед', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 2, defaultRestSec: 45, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 20 }),
  defineExercise({ id: 'gpp_core_russian', name: 'Русские скручивания', pattern: 'core', equipment: 'none', muscles: ['obliques'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 16 }),
  defineExercise({ id: 'gpp_core_mountain', name: 'Скалолаз', pattern: 'core', equipment: 'none', muscles: ['core'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 24 }),
  defineExercise({ id: 'gpp_core_dead_bug', name: 'Dead bug', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 1, defaultRestSec: 45, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_core_bird_dog', name: 'Bird dog', pattern: 'core', equipment: 'none', muscles: ['core'], difficulty: 1, defaultRestSec: 45, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_core_v_up', name: 'V-ups', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_core_toes_bar', name: 'К носкам (подготовка)', pattern: 'core', equipment: 'bar', muscles: ['abs'], difficulty: 4, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 6 }),
  defineExercise({ id: 'gpp_core_windshield', name: 'Дворники ноги', pattern: 'core', equipment: 'bar', muscles: ['abs'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_core_hanging_knee', name: 'Колени к локтям', pattern: 'core', equipment: 'bar', muscles: ['abs'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_core_pallof', name: 'Анти-ротация (палоф)', pattern: 'core', equipment: 'none', muscles: ['obliques'], difficulty: 2, defaultRestSec: 60, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 25, isStatic: true }),
  defineExercise({ id: 'gpp_core_copenhagen', name: 'Copenhagen (бок)', pattern: 'core', equipment: 'none', muscles: ['adductors'], difficulty: 3, defaultRestSec: 60, progressionRule: 'time+5s', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'seconds', defaultTargetSec: 20, isStatic: true }),
  defineExercise({ id: 'gpp_core_reverse_plank', name: 'Обратная планка', pattern: 'core', equipment: 'none', muscles: ['posterior'], difficulty: 2, defaultRestSec: 45, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'gpp_core_suitcase', name: 'Чемодан (одна рука)', pattern: 'core', equipment: 'none', muscles: ['obliques'], difficulty: 2, defaultRestSec: 60, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 25, isStatic: true }),
  defineExercise({ id: 'gpp_core_bear', name: 'Медведь (crawl hold)', pattern: 'core', equipment: 'none', muscles: ['core'], difficulty: 2, defaultRestSec: 60, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'gpp_core_hollow_rock', name: 'Hollow rock', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_core_plank_shoulder', name: 'Планка + касание плеча', pattern: 'core', equipment: 'none', muscles: ['core'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_core_ab_wheel', name: 'Скручивания ноги 90°', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 15 }),
  defineExercise({ id: 'gpp_core_hanging_l', name: 'Вис L (статика)', pattern: 'core', equipment: 'bar', muscles: ['abs'], difficulty: 4, defaultRestSec: 90, progressionRule: 'time+3s', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'seconds', defaultTargetSec: 15, isStatic: true }),
  defineExercise({ id: 'gpp_core_dragon_flag', name: 'Дракон флаг (негатив)', pattern: 'core', equipment: 'none', muscles: ['abs'], difficulty: 5, defaultRestSec: 120, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('ayanakoji'), measure: 'reps', defaultTargetReps: 3 }),
  defineExercise({ id: 'gpp_core_side_plank_star', name: 'Звезда боковая', pattern: 'core', equipment: 'none', muscles: ['obliques'], difficulty: 3, defaultRestSec: 60, progressionRule: 'time+5s', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'seconds', defaultTargetSec: 25, isStatic: true }),
  defineExercise({ id: 'gpp_core_prone_cobra', name: 'Кобра (удержание)', pattern: 'core', equipment: 'none', muscles: ['back'], difficulty: 1, defaultRestSec: 45, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'gpp_core_hollow_arch_alt', name: 'Hollow ↔ Arch', pattern: 'core', equipment: 'none', muscles: ['core'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 8 }),
];
