import type { CatalogExercise } from '@/core/domain/types';
import { allTiers, defineExercise, tiersFromMin } from './catalog-utils';

const K: CatalogExercise['workoutKinds'] = ['gpp_pull'];

export const GPP_PULL_EXERCISES: CatalogExercise[] = [
  defineExercise({ id: 'gpp_pull_pullup', name: 'Подтягивания', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 3, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'reps', defaultTargetReps: 6 }),
  defineExercise({ id: 'gpp_pull_australian', name: 'Австралийские подтягивания', pattern: 'pull', equipment: 'bar', muscles: ['back'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('beginner'), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_pull_neutral', name: 'Подтягивания нейтральным хватом', pattern: 'pull', equipment: 'bar', muscles: ['lat', 'biceps'], difficulty: 3, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'reps', defaultTargetReps: 6 }),
  defineExercise({ id: 'gpp_pull_chin', name: 'Подтягивания обратным хватом (бицепс)', pattern: 'pull', equipment: 'bar', muscles: ['biceps'], difficulty: 3, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_pull_wide', name: 'Подтягивания широким хватом', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 4, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 6 }),
  defineExercise({ id: 'gpp_pull_close', name: 'Узкий хват', pattern: 'pull', equipment: 'bar', muscles: ['biceps'], difficulty: 3, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'reps', defaultTargetReps: 6 }),
  defineExercise({ id: 'gpp_pull_neg', name: 'Негативы', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 2, defaultRestSec: 90, progressionRule: 'slow', workoutKinds: K, tiers: tiersFromMin('beginner'), measure: 'reps', defaultTargetReps: 4 }),
  defineExercise({ id: 'gpp_pull_scap', name: 'Шраги в висе (лопатки)', pattern: 'pull', equipment: 'bar', muscles: ['back'], difficulty: 1, defaultRestSec: 60, progressionRule: 'reps+2', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_pull_hang', name: 'Пассивный вис', pattern: 'pull', equipment: 'bar', muscles: ['grip'], difficulty: 1, defaultRestSec: 60, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 30, isStatic: true }),
  defineExercise({ id: 'gpp_pull_active_hang', name: 'Вис на перекладине (активный)', pattern: 'pull', equipment: 'bar', muscles: ['grip'], difficulty: 2, defaultRestSec: 60, progressionRule: 'time+5s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 25, isStatic: true }),
  defineExercise({ id: 'gpp_pull_invert', name: 'Горизонтальные низкие', pattern: 'pull', equipment: 'bar', muscles: ['back'], difficulty: 1, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: allTiers(), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_pull_invert_high', name: 'Горизонтальные высокие', pattern: 'pull', equipment: 'bar', muscles: ['back'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_pull_archer', name: 'Арчер подтяг', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 5, defaultRestSec: 120, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 3 }),
  defineExercise({ id: 'gpp_pull_typewriter', name: 'Тайпрайтер', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 5, defaultRestSec: 120, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('ayanakoji'), measure: 'reps', defaultTargetReps: 3 }),
  defineExercise({ id: 'gpp_pull_mu_neg', name: 'Негатив выхода', pattern: 'pull', equipment: 'bar', muscles: ['full'], difficulty: 5, defaultRestSec: 120, progressionRule: 'quality', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 3 }),
  defineExercise({ id: 'gpp_pull_commando', name: 'Коммандо подтяг', pattern: 'pull', equipment: 'bar', muscles: ['back'], difficulty: 4, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 5 }),
  defineExercise({ id: 'gpp_pull_pullover', name: 'Пуловер на турнике', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_pull_front_lever_tuck', name: 'Фронт левер (tuck)', pattern: 'pull', equipment: 'bar', muscles: ['core'], difficulty: 4, defaultRestSec: 90, progressionRule: 'time+3s', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'seconds', defaultTargetSec: 12, isStatic: true }),
  defineExercise({ id: 'gpp_pull_back_lever_tuck', name: 'Бэк левер (tuck)', pattern: 'pull', equipment: 'bar', muscles: ['back'], difficulty: 5, defaultRestSec: 120, progressionRule: 'time+2s', workoutKinds: K, tiers: tiersFromMin('ayanakoji'), measure: 'seconds', defaultTargetSec: 8, isStatic: true }),
  defineExercise({ id: 'gpp_pull_row_feet', name: 'Тяга ноги на земле', pattern: 'pull', equipment: 'bar', muscles: ['back'], difficulty: 2, defaultRestSec: 60, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('beginner'), measure: 'reps', defaultTargetReps: 12 }),
  defineExercise({ id: 'gpp_pull_isometric_top', name: 'Удержание вверху', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 3, defaultRestSec: 75, progressionRule: 'time+3s', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'seconds', defaultTargetSec: 15, isStatic: true }),
  defineExercise({ id: 'gpp_pull_isometric_mid', name: 'Удержание в середине', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 4, defaultRestSec: 90, progressionRule: 'time+2s', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'seconds', defaultTargetSec: 10, isStatic: true }),
  defineExercise({ id: 'gpp_pull_rings_skin', name: 'Skin the cat (подготовка)', pattern: 'pull', equipment: 'bar', muscles: ['shoulders'], difficulty: 4, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 4 }),
  defineExercise({ id: 'gpp_pull_curl', name: 'Подтяг до подбородка (медленно)', pattern: 'pull', equipment: 'bar', muscles: ['biceps'], difficulty: 2, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('novice'), measure: 'reps', defaultTargetReps: 8 }),
  defineExercise({ id: 'gpp_pull_eccentric', name: 'Эксцентрик 5 сек', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 3, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 5 }),
  defineExercise({ id: 'gpp_pull_climb', name: 'Подъём колен к груди в висе', pattern: 'pull', equipment: 'bar', muscles: ['core'], difficulty: 3, defaultRestSec: 75, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'reps', defaultTargetReps: 10 }),
  defineExercise({ id: 'gpp_pull_twist', name: 'Подтяг с поворотом', pattern: 'pull', equipment: 'bar', muscles: ['obliques'], difficulty: 4, defaultRestSec: 90, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'reps', defaultTargetReps: 5 }),
  defineExercise({ id: 'gpp_pull_one_arm_assist', name: 'Одна рука (ассист)', pattern: 'pull', equipment: 'bar', muscles: ['lat'], difficulty: 5, defaultRestSec: 120, progressionRule: 'reps+1', workoutKinds: K, tiers: tiersFromMin('ayanakoji'), measure: 'reps', defaultTargetReps: 2 }),
  defineExercise({ id: 'gpp_pull_dead_hang_long', name: 'Длинный вис (статика)', pattern: 'pull', equipment: 'bar', muscles: ['grip'], difficulty: 2, defaultRestSec: 60, progressionRule: 'time+10s', workoutKinds: K, tiers: allTiers(), measure: 'seconds', defaultTargetSec: 45, isStatic: true }),
  defineExercise({ id: 'gpp_pull_bar_support', name: 'Удержание над турником', pattern: 'pull', equipment: 'bar', muscles: ['grip'], difficulty: 3, defaultRestSec: 75, progressionRule: 'time+5s', workoutKinds: K, tiers: tiersFromMin('medium'), measure: 'seconds', defaultTargetSec: 20, isStatic: true }),
  defineExercise({ id: 'gpp_pull_false_grip', name: 'Ложный хват вис', pattern: 'pull', equipment: 'bar', muscles: ['forearms'], difficulty: 4, defaultRestSec: 90, progressionRule: 'time+3s', workoutKinds: K, tiers: tiersFromMin('pro'), measure: 'seconds', defaultTargetSec: 15, isStatic: true }),
];
