/** Default integration / stage-gate thresholds (adapted via integration-params EMA). */
export const INTEGRATION_THRESHOLDS = {
  qualifyingDaysRequired: 10,
  softScoreRequired: 80,
  readinessHistoryDays: 14,
  bottleneckTieSpread: 2,
  bottleneckDegraded: 40,
  globalWeak: 60,
  auditIntervalDays: 7,

  synergyGapPenalty: 0.4,

  /** Foundation → regulation */
  f2r: {
    foundationMin: 68,
    globalMin: 58,
    complianceMin: 62,
    debriefMin: 75,
    briefingMin: 50,
    bftMaxDays: 90,
    trainingMin7d: 2,
    foundationDays14Min: 10,
    foundationHistoryFloor: 65,
  },
  /** Regulation → mind */
  r2m: {
    foundationFloor: 52,
    regulationMin: 70,
    globalMin: 62,
    regulationPractice14Min: 4,
    hrvDays7Min: 3,
    debriefMin: 80,
    resonant7Min: 2,
    complianceMin: 65,
    regulationHistoryFloor: 60,
    foundationHistoryFloor: 50,
  },
  /** Mind → influence */
  m2i: {
    foundationFloor: 48,
    regulationFloor: 50,
    mindMin: 68,
    globalMin: 65,
    mindPractice14Min: 3,
    scenarios14Min: 1,
    complianceMin: 70,
    decisions14Min: 1,
    mindHistoryFloor: 55,
    foundationHistoryFloor: 48,
    regulationHistoryFloor: 50,
  },
  demotion: {
    frFoundationMax: 40,
    frRegulationMax: 38,
    frWeakDays10: 7,
    regulationWeakMax: 42,
    regulationWeakDays7: 5,
    mindWeakMax: 45,
    mindWeakDays7: 5,
  },
  params: {
    complianceTargetDefault: 62,
    debriefTargetDefault: 75,
    synergyGapToleranceDefault: 2,
    complianceMin: 50,
    complianceMax: 85,
    debriefMin: 60,
    debriefMax: 95,
    synergyGapMin: 1,
    synergyGapMax: 6,
    auditIntervalMin: 5,
    auditIntervalMax: 14,
  },
} as const;
