/** Calibrated mind scoring and cognitive safety gates. */
export const MIND_THRESHOLDS = {
  coldStart: 50,
  coldLookbackDays: 14,
  chessCountTarget7d: 5,
  chessMinutesTarget7d: 150,
  reflectTarget7d: 5,
  chessCountScoreMax: 25,
  chessMinScoreMax: 20,
  reflectScoreMax: 25,
  scenarioScoreMax: 15,
  decisionScoreMax: 10,
  studyBonusMax: 5,
  closureBonusHigh: 5,
  closureBonusMid: 2,
  closurePctHigh: 70,
  closurePctMid: 40,
  weeklyReadingBonus: 5,
  foundationCapBelow: 45,
  regulationCapBelow: 40,
  readinessCapWhenLowBase: 55,
  throttleFoundationBelow: 45,
  throttleRegulationBelow: 40,
  closureLowPct: 40,
  chessDoseMin: 15,
  chessDoseMax: 90,
  chessThrottleMaxMin: 20,
  ratingZProgress: 0.5,
  ratingZRegression: -0.5,
  ratingProgressBonus: 3,
  swotToleranceMin: 0.35,
  focusMin: 1,
  focusMax: 5,
} as const;
