import type { BarExercise } from '@/core/domain/types';

export const BAR_EXERCISES: BarExercise[] = [
  {
    id: 'pullup',
    name: 'Подтягивания',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['lat', 'biceps'],
    difficulty: 3,
    defaultRestSec: 90,
    progressionRule: 'reps+1 when all sets hit target',
  },
  {
    id: 'pullup_wide',
    name: 'Подтягивания широким хватом',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['lat'],
    difficulty: 4,
    defaultRestSec: 90,
    progressionRule: 'reps+1',
  },
  {
    id: 'pullup_close',
    name: 'Подтягивания узким хватом',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['biceps', 'lat'],
    difficulty: 3,
    defaultRestSec: 90,
    progressionRule: 'reps+1',
  },
  {
    id: 'australian',
    name: 'Австралийские подтягивания',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['upper_back'],
    difficulty: 2,
    defaultRestSec: 75,
    progressionRule: 'reps+1',
  },
  {
    id: 'negative_pull',
    name: 'Негативные подтягивания',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['lat'],
    difficulty: 2,
    defaultRestSec: 90,
    progressionRule: 'slow eccentrics',
  },
  {
    id: 'dead_hang',
    name: 'Вис на турнике',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['grip', 'shoulders'],
    difficulty: 1,
    defaultRestSec: 60,
    progressionRule: 'time+5s',
  },
  {
    id: 'dip',
    name: 'Отжимания на брусьях',
    pattern: 'push',
    equipment: 'dip',
    muscles: ['chest', 'triceps'],
    difficulty: 3,
    defaultRestSec: 60,
    progressionRule: 'reps+1',
  },
  {
    id: 'dip_assisted',
    name: 'Отжимания на брусьях (ноги на земле)',
    pattern: 'push',
    equipment: 'dip',
    muscles: ['chest', 'triceps'],
    difficulty: 2,
    defaultRestSec: 60,
    progressionRule: 'reps+1',
  },
  {
    id: 'knee_raise',
    name: 'Подъём коленей в висе',
    pattern: 'core',
    equipment: 'bar',
    muscles: ['abs'],
    difficulty: 2,
    defaultRestSec: 60,
    progressionRule: 'reps+1',
  },
  {
    id: 'lsit_tuck',
    name: 'L-sit (согнутые колени)',
    pattern: 'core',
    equipment: 'bar',
    muscles: ['abs', 'hip_flexors'],
    difficulty: 3,
    defaultRestSec: 60,
    progressionRule: 'hold+3s',
  },
  {
    id: 'plank',
    name: 'Планка',
    pattern: 'core',
    equipment: 'none',
    muscles: ['core'],
    difficulty: 1,
    defaultRestSec: 45,
    progressionRule: 'time+10s',
  },
  {
    id: 'squat_bw',
    name: 'Приседания с весом тела',
    pattern: 'legs',
    equipment: 'none',
    muscles: ['quads', 'glutes'],
    difficulty: 1,
    defaultRestSec: 60,
    progressionRule: 'reps+2',
  },
  {
    id: 'lunge',
    name: 'Выпады',
    pattern: 'legs',
    equipment: 'none',
    muscles: ['quads', 'glutes'],
    difficulty: 2,
    defaultRestSec: 60,
    progressionRule: 'reps+1 per leg',
  },
  {
    id: 'scapular_pull',
    name: 'Скапулярные подтягивания',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['upper_back'],
    difficulty: 1,
    defaultRestSec: 60,
    progressionRule: 'reps+2',
  },
  {
    id: 'chin_up',
    name: 'Подтягивания обратным хватом',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['biceps', 'lat'],
    difficulty: 3,
    defaultRestSec: 90,
    progressionRule: 'reps+1',
  },
  {
    id: 'pushup_bar',
    name: 'Отжимания от турника (ноги на земле)',
    pattern: 'push',
    equipment: 'bar',
    muscles: ['chest'],
    difficulty: 2,
    defaultRestSec: 60,
    progressionRule: 'reps+1',
  },
  {
    id: 'hollow_hold',
    name: 'Hollow body hold',
    pattern: 'core',
    equipment: 'none',
    muscles: ['abs'],
    difficulty: 2,
    defaultRestSec: 45,
    progressionRule: 'time+5s',
  },
  {
    id: 'leg_raise',
    name: 'Подъём ног в висе',
    pattern: 'core',
    equipment: 'bar',
    muscles: ['abs'],
    difficulty: 4,
    defaultRestSec: 75,
    progressionRule: 'reps+1',
  },
  {
    id: 'bulgarian_split',
    name: 'Болгарские выпады',
    pattern: 'legs',
    equipment: 'none',
    muscles: ['quads'],
    difficulty: 3,
    defaultRestSec: 60,
    progressionRule: 'reps+1',
  },
  {
    id: 'jump_squat',
    name: 'Прыжковые приседания',
    pattern: 'legs',
    equipment: 'none',
    muscles: ['quads'],
    difficulty: 2,
    defaultRestSec: 75,
    progressionRule: 'reps+2',
  },
  {
    id: 'dip_negative',
    name: 'Негативы на брусьях',
    pattern: 'push',
    equipment: 'dip',
    muscles: ['chest'],
    difficulty: 2,
    defaultRestSec: 90,
    progressionRule: 'slow eccentrics',
  },
  {
    id: 'active_hang',
    name: 'Активный вис',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['grip'],
    difficulty: 2,
    defaultRestSec: 60,
    progressionRule: 'time+5s',
  },
  {
    id: 'lsit_advanced',
    name: 'L-sit (прямые ноги)',
    pattern: 'core',
    equipment: 'bar',
    muscles: ['abs'],
    difficulty: 5,
    defaultRestSec: 75,
    progressionRule: 'hold+2s',
  },
  {
    id: 'muscle_up_neg',
    name: 'Негатив выхода силой',
    pattern: 'pull',
    equipment: 'bar',
    muscles: ['full'],
    difficulty: 5,
    defaultRestSec: 120,
    progressionRule: 'quality reps',
  },
  {
    id: 'pike_pushup',
    name: 'Пике-отжимания',
    pattern: 'push',
    equipment: 'none',
    muscles: ['shoulders'],
    difficulty: 2,
    defaultRestSec: 60,
    progressionRule: 'reps+1',
  },
];

export function getExerciseById(id: string): BarExercise | undefined {
  return BAR_EXERCISES.find((e) => e.id === id);
}
